# Generated by Django 2.0.5 on 2019-12-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bs_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('cost', models.FloatField()),
                ('turnover', models.FloatField()),
                ('gross_profit', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '营业数据',
                'db_table': 'bs_data',
            },
        ),
        migrations.CreateModel(
            name='goods_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bar_code', models.CharField(db_index=True, max_length=32)),
                ('qgp', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '商品数据',
                'db_table': 'goods_data',
            },
        ),
        migrations.CreateModel(
            name='goods_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bar_code', models.CharField(db_index=True, max_length=32)),
                ('qgp', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '商品列表',
                'db_table': 'goods_list',
            },
        ),
        migrations.CreateModel(
            name='goods_quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(db_index=True, max_length=32)),
                ('stock_nums', models.IntegerField(default=2)),
                ('date_nums', models.IntegerField(default=30)),
                ('add_date', models.DateField()),
                ('state', models.IntegerField(default=1, max_length=2)),
                ('store_id', models.IntegerField()),
                ('goods_id', models.ForeignKey(db_column='goods_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='businessdata.goods_list')),
            ],
            options={
                'verbose_name_plural': '保质期检查单',
                'db_table': 'goods_quality',
            },
        ),
        migrations.CreateModel(
            name='huayu_businessdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('cost', models.FloatField()),
                ('turnover', models.FloatField()),
                ('gross_profit', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '营业数据',
                'db_table': 'huayu_businessdata',
            },
        ),
        migrations.CreateModel(
            name='order_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=32)),
                ('goods_name', models.CharField(max_length=64)),
                ('goods_code', models.CharField(max_length=64)),
                ('goods_num', models.IntegerField()),
                ('goods_money', models.FloatField()),
                ('form_date', models.DateField()),
                ('form_time', models.TimeField()),
                ('form_money', models.FloatField()),
                ('form_money_true', models.FloatField()),
                ('store_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '订单列表',
                'db_table': 'order_form',
            },
        ),
        migrations.CreateModel(
            name='stock_width_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(db_index=True, max_length=32)),
                ('store_id', models.IntegerField()),
                ('state', models.IntegerField(default=1)),
                ('stock_type', models.IntegerField()),
                ('add_date', models.DateField()),
                ('goods_id', models.ForeignKey(db_column='goods_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='businessdata.goods_list')),
            ],
            options={
                'verbose_name_plural': '订货单',
                'db_table': 'stock_width_goods',
            },
        ),
        migrations.CreateModel(
            name='store_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adds', models.TextField()),
            ],
            options={
                'verbose_name_plural': '门店列表',
                'db_table': 'store_list',
            },
        ),
        migrations.AddField(
            model_name='goods_list',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='businessdata.store_list'),
        ),
        migrations.AddField(
            model_name='goods_data',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='businessdata.store_list'),
        ),
        migrations.AddField(
            model_name='bs_data',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='businessdata.store_list'),
        ),
    ]
