# Generated by Django 2.0.5 on 2019-12-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0003_auto_20191221_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_quality',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='businessdata.goods_list'),
        ),
        migrations.AddField(
            model_name='stock_width_goods',
            name='store_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
