# Generated by Django 2.0.5 on 2019-12-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0004_auto_20191221_1157'),
    ]

    operations = [

    ]
