# Generated by Django 2.0.5 on 2019-12-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0005_remove_stock_width_goods_goods_id'),
    ]

    operations = [

    ]
