# Generated by Django 2.0.5 on 2019-12-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0006_remove_stock_width_goods_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_width_goods',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='businessdata.goods_list'),
        ),
    ]
