# Generated by Django 2.0.5 on 2019-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0007_stock_width_goods_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_list',
            name='classify',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods_list',
            name='stock_nums',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
